"""LAN device scanner package — discovery, enrichment, and scan pipeline."""

from app.domain.services.device_type_inference import guess_device_type_detailed

from .constants import (
    _IO_EXECUTOR,
    _MAC_LOOKUP_AVAILABLE,
    _PORT_SERVICES,
    _SCAPY_AVAILABLE,
    ARP,
    IO_EXECUTOR,
    MAC_LOOKUP_AVAILABLE,
    PORT_SERVICES,
    SCAPY_AVAILABLE,
    AsyncMacLookup,
    Ether,
    srp,
)
from .enrichment import (
    _build_upnp_cache,
    _enrich_device,
    _fetch_upnp_for_ip,
    build_upnp_cache,
    enrich_device,
    fetch_upnp_for_ip,
)
from .metadata import (
    _build_scan_metadata,
    _extract_mac_oui,
    _guess_os_from_ttl,
    _map_ports_to_services,
    _persist_scan_fields,
    build_scan_metadata,
    extract_mac_oui,
    guess_os_from_ttl,
    map_ports_to_services,
    persist_scan_fields,
)
from .network import (
    _detect_prefix_length,
    _ip_in_scan_networks,
    _local_ipv4_addresses,
    detect_default_gateway_ips,
    detect_local_network,
    detect_local_networks,
    detect_prefix_length,
    ip_in_scan_networks,
    local_ipv4_addresses,
)
from .pipeline import (
    _find_unknown_devices,
    _log_scan_result,
    _run_scan,
    find_unknown_devices,
    log_scan_result,
    run_device_scan,
)
from .probe import Scanner

__all__ = [
    'ARP',
    'AsyncMacLookup',
    'Ether',
    'IO_EXECUTOR',
    'MAC_LOOKUP_AVAILABLE',
    'PORT_SERVICES',
    'SCAPY_AVAILABLE',
    'Scanner',
    'build_scan_metadata',
    'build_upnp_cache',
    'detect_default_gateway_ips',
    'detect_local_network',
    'detect_local_networks',
    'detect_prefix_length',
    'enrich_device',
    'extract_mac_oui',
    'fetch_upnp_for_ip',
    'find_unknown_devices',
    'guess_device_type_detailed',
    'guess_os_from_ttl',
    'ip_in_scan_networks',
    'local_ipv4_addresses',
    'log_scan_result',
    'map_ports_to_services',
    'persist_scan_fields',
    'run_device_scan',
    'srp',
    '_IO_EXECUTOR',
    '_MAC_LOOKUP_AVAILABLE',
    '_PORT_SERVICES',
    '_SCAPY_AVAILABLE',
    '_build_scan_metadata',
    '_build_upnp_cache',
    '_detect_prefix_length',
    '_enrich_device',
    '_extract_mac_oui',
    '_fetch_upnp_for_ip',
    '_find_unknown_devices',
    '_guess_os_from_ttl',
    '_ip_in_scan_networks',
    '_local_ipv4_addresses',
    '_log_scan_result',
    '_map_ports_to_services',
    '_persist_scan_fields',
    '_run_scan',
]
